### ISSUE TITLE
Improved navigation menu for small screens/narrow windows

### ISSUE THREAD

**Issue by AlnisS** [UWCubeSat/hsl-website#7]
Currently, the site is challenging (or impossible) to navigate on small screens or narrow windows, especially some mobile phones.

**Comment by AlnisS** [comment]
We may be able to work around this creatively with a relatively small amount of CSS and JavaScript.

For example, a media query for narrow screens:
```css
@media only screen and (max-width: 600px) {
    /* rules */
}
```

...which moves the menu items off to the left side of the screen:
```css
element.style {
    position: absolute;
    left: 0;
    top: 0;
    transform: translate(-200px, 0);
}
```

...and adds a button to toggle translating the whole body to the right by the same amount to toggle the menu opening:
```css
body {
    transform: translate(200px, 0);
}
```
